"""initial_schema

Revision ID: e8b004907f24
Revises: 
Create Date: 2026-04-17 08:37:39.282706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8b004907f24'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_codes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('attempts', sa.SmallInteger(), server_default='0', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_otp_lookup', 'otp_codes', ['phone_number', 'purpose', 'is_used'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), server_default='Pakistan', nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('age', sa.SmallInteger(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=True),
    sa.Column('cnic_number', sa.String(length=20), nullable=True),
    sa.Column('cnic_encrypted', sa.Text(), nullable=True),
    sa.Column('cnic_number_masked', sa.String(length=20), nullable=True),
    sa.Column('verification_tier', sa.SmallInteger(), server_default='0', nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_superuser', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_locked', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('is_flagged', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('risk_score', sa.SmallInteger(), server_default='0', nullable=True),
    sa.Column('account_type', sa.String(length=20), server_default='individual', nullable=True),
    sa.Column('biometric_enabled', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('cnic_verified', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('biometric_verified', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('fingerprint_verified', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('nadra_verified', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('fcm_token', sa.Text(), nullable=True),
    sa.Column('login_attempts', sa.SmallInteger(), server_default='0', nullable=True),
    sa.Column('profile_photo_url', sa.Text(), nullable=True),
    sa.Column('member_since', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index('idx_users_phone', 'users', ['phone_number'], unique=False)
    op.create_index('idx_users_tier', 'users', ['verification_tier'], unique=False)
    op.create_table('ai_insights',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('health_score', sa.SmallInteger(), nullable=True),
    sa.Column('health_label', sa.Text(), nullable=True),
    sa.Column('top_categories', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('monthly_comparison', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('savings_tips', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('unusual_spending', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('roast_content', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('bank_accounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('account_number_encrypted', sa.String(), nullable=False),
    sa.Column('account_number_masked', sa.String(length=25), nullable=False),
    sa.Column('account_title', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_splits',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('split_type', sa.String(length=20), server_default='equal', nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('total_amount > 0', name='ck_split_amount_positive'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('ntn_number', sa.String(length=50), nullable=True),
    sa.Column('verification_status', sa.String(length=30), server_default='pending', nullable=True),
    sa.Column('rejection_reasons', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('ai_analysis_result', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('device_registry',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('device_os', sa.String(length=100), nullable=True),
    sa.Column('is_trusted', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('trusted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_fingerprint', name='uq_device_user_fp')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('cloudinary_public_id', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fingerprint_scans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('finger_index', sa.SmallInteger(), nullable=False),
    sa.Column('feature_hash', sa.String(length=255), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('finger_index BETWEEN 1 AND 8', name='ck_finger_index_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('high_yield_deposits',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('period_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.Column('expected_interest', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('early_withdrawal', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('matured_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount > 0', name='ck_hyd_amount_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insurance_policies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('policy_type', sa.String(length=100), nullable=False),
    sa.Column('plan_name', sa.String(length=255), nullable=False),
    sa.Column('premium', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('coverage', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('return_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('expected_return', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('actual_return', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount > 0', name='ck_investment_amount_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_audit',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notif_user', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_table('offer_templates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reward_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_days', sa.Integer(), server_default='30', nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('device_info', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('rewards',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_earned', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=True),
    sa.Column('pending', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=True),
    sa.Column('claimed', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('saving_goals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('goal_name', sa.String(length=255), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('saved_amount', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=True),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('goal_achieved', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('withdraw_count', sa.SmallInteger(), server_default='0', nullable=True),
    sa.Column('auto_deduct_enabled', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('auto_deduct_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('auto_deduct_freq', sa.String(length=20), nullable=True),
    sa.Column('next_deduction_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_deduction_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('saved_amount >= 0', name='ck_goal_saved_non_negative'),
    sa.CheckConstraint('target_amount > 0', name='ck_goal_target_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('reference_number', sa.String(length=30), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fee', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=True),
    sa.Column('cashback_earned', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=True),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('recipient_id', sa.UUID(), nullable=True),
    sa.Column('purpose', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('flag_reason', sa.Text(), nullable=True),
    sa.Column('flagged_by', sa.UUID(), nullable=True),
    sa.Column('flagged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tx_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('amount > 0', name='ck_txn_amount_positive'),
    sa.ForeignKeyConstraint(['flagged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    op.create_index('idx_txn_purpose', 'transactions', ['purpose'], unique=False)
    op.create_index('idx_txn_recipient', 'transactions', ['recipient_id', 'created_at'], unique=False)
    op.create_index('idx_txn_sender', 'transactions', ['sender_id', 'created_at'], unique=False)
    op.create_index('idx_txn_status', 'transactions', ['status'], unique=False)
    op.create_table('trusted_circle',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('user_id != contact_id', name='ck_no_self_trust'),
    sa.ForeignKeyConstraint(['contact_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'contact_id', name='uq_trusted_circle')
    )
    op.create_table('virtual_cards',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('card_name', sa.String(length=100), nullable=True),
    sa.Column('card_holder_name', sa.String(length=255), nullable=False),
    sa.Column('card_type', sa.String(length=20), server_default='virtual', nullable=True),
    sa.Column('card_network', sa.String(length=20), server_default='visa', nullable=True),
    sa.Column('card_number_hash', sa.String(length=255), nullable=False),
    sa.Column('last_four', sa.String(length=4), nullable=False),
    sa.Column('cvv_hash', sa.String(length=255), nullable=False),
    sa.Column('expiry_month', sa.SmallInteger(), nullable=False),
    sa.Column('expiry_year', sa.SmallInteger(), nullable=False),
    sa.Column('gradient_theme', sa.String(length=50), server_default='blue', nullable=True),
    sa.Column('pin_hash', sa.String(length=255), nullable=True),
    sa.Column('spending_limit', sa.Numeric(precision=10, scale=2), server_default='25000.00', nullable=True),
    sa.Column('daily_limit', sa.Numeric(precision=10, scale=2), server_default='25000.00', nullable=True),
    sa.Column('monthly_limit', sa.Numeric(precision=10, scale=2), server_default='500000.00', nullable=True),
    sa.Column('monthly_spent', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=True),
    sa.Column('monthly_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='active', nullable=True),
    sa.Column('is_frozen', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_online_enabled', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('is_international_enabled', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_atm_enabled', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_contactless', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('physical_requested', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='PKR', nullable=True),
    sa.Column('is_frozen', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('daily_limit', sa.Numeric(precision=12, scale=2), server_default='25000.00', nullable=True),
    sa.Column('daily_spent', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=True),
    sa.Column('limit_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cashback_pending', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=True),
    sa.Column('cashback_claimed', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('balance >= 0.00', name='ck_wallet_balance_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('zakat_calculations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cash_pkr', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=True),
    sa.Column('gold_grams', sa.Numeric(precision=8, scale=3), server_default='0.000', nullable=True),
    sa.Column('silver_grams', sa.Numeric(precision=8, scale=3), server_default='0.000', nullable=True),
    sa.Column('business_inventory_pkr', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=True),
    sa.Column('receivables_pkr', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=True),
    sa.Column('gold_rate_per_gram', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('silver_rate_per_gram', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('usd_to_pkr_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('total_assets_pkr', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('nisab_threshold_pkr', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('zakat_due_pkr', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_paid', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_actions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('target_user_id', sa.UUID(), nullable=True),
    sa.Column('target_txn_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('action_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_txn_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fraud_flags',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), server_default='low', nullable=True),
    sa.Column('is_resolved', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reward_offers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_spent', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=True),
    sa.Column('reward_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['offer_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('split_participants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('split_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('declined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['split_id'], ['bill_splits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('split_id', 'user_id', name='uq_split_participant')
    )
    op.create_table('reward_transactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('offer_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['reward_offers.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reward_transactions')
    op.drop_table('split_participants')
    op.drop_table('reward_offers')
    op.drop_table('fraud_flags')
    op.drop_table('admin_actions')
    op.drop_table('zakat_calculations')
    op.drop_table('wallets')
    op.drop_table('virtual_cards')
    op.drop_table('trusted_circle')
    op.drop_index('idx_txn_status', table_name='transactions')
    op.drop_index('idx_txn_sender', table_name='transactions')
    op.drop_index('idx_txn_recipient', table_name='transactions')
    op.drop_index('idx_txn_purpose', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('saving_goals')
    op.drop_table('rewards')
    op.drop_table('refresh_tokens')
    op.drop_table('offer_templates')
    op.drop_index('idx_notif_user', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('login_audit')
    op.drop_table('investments')
    op.drop_table('insurance_policies')
    op.drop_table('high_yield_deposits')
    op.drop_table('fingerprint_scans')
    op.drop_table('documents')
    op.drop_table('device_registry')
    op.drop_table('chat_sessions')
    op.drop_table('business_profiles')
    op.drop_table('bill_splits')
    op.drop_table('bank_accounts')
    op.drop_table('ai_insights')
    op.drop_index('idx_users_tier', table_name='users')
    op.drop_index('idx_users_phone', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_otp_lookup', table_name='otp_codes')
    op.drop_table('otp_codes')
    # ### end Alembic commands ###
